### ISSUE TITLE
Improve recipe building algorithm

### ISSUE THREAD

**Issue by gabLaroche** [gabLaroche/recipe-ipsum#6]
The algorithm is flawed when creating recipes, especially when there is either an ingredient that appears too many times in the directions or not all the ingredients are used

**Comment by sylvaindessureault** [comment]
Hi Gabriel!
I'd love to work on this!

**Comment by gabLaroche** [comment]
Awesome! I assigned the issue to you

**Comment by sylvaindessureault** [comment]
Great! This is a great project, so I'll start working on this right away. Thanks!!!

**Comment by sylvaindessureault** [comment]
@gabLaroche, I had started to work on this, but since there are some interesting, facilitating and somewhat impacting changes potentially coming in [#13](https://github.com/gabLaroche/recipe-ipsum/pull/13) I will wait until this is merged and update my fork and continue the work on this issue, if that's OK with you.

**Comment by gabLaroche** [comment]
That is perfectly Ok with me, the last thing I want to cause with this project is stress! I just merged the PR!

**Comment by sylvaindessureault** [comment]
[#17](https://github.com/gabLaroche/recipe-ipsum/pull/17)

@gabLaroche, let me know if you want me to comment the code further.

Also, I was wondering if it was by design that the copy to clipboard functionality didn't include the numbering for the steps?

**Comment by gabLaroche** [comment]
@sylvaindessureault Nope not by design, that is a bug :) I guess we could hide the `<ol>`'s list-style-type and add the numbering in a span.
